apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Welcome to my website</title></head>
    <body>
    <h1>Hello from my website!</h1>
    </body>
    </html>

