apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Welcome to my website</title></head>
    <body>
    <h1>Hello from my website!</h1>
    </body>
    </html>
  default.conf: |
    server {
        listen       8081;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
     server {
        listen 45807;
        location / {
            default_type text/html;
            return 200 "<html><body><h1>Hello from my website!</h1><p>This is a simple webpage served by nginx.</p></body></html>";
        }
    }


